# Generated by Django 4.2.24 on 2025-09-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_principal",
            "0002_combo_competencia_item_itemcombo_municipio_perfil_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competencia",
            name="item",
        ),
    ]
